[package]
name = "rcap"
version = "0.1.0"
edition = "2024_07"

[cairo]
enable-gas = false

[dependencies]
cairo_execute = "2.19.6"

[dev-dependencies]
cairo_test = "2.19.6"

[[target.executable]]
name = "main"
function = "rcap::main"
